

#include src/arm/makefile

OBJS	+= \
	Main.o \
	Common/Log.o \
	Core/Memory.o \
	Core/Arm/Arm.o \
	Core/Arm/ArmUnicornInterface.o \
	Core/Loader/ElfLoader.o \
	Core/Loader/relocate.o \
	Core/HLE/Kernel.o \
	Core/HLE/Module.o \
	Core/HLE/SceSysmem.o \
	Core/HLE/SceThreadmgr.o